[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200

; Le decimos a PlatformIO que descargue las dependencias de Arduino automáticamente
lib_deps = 
	adafruit/Adafruit BME280 Library @ 2.2.4
	adafruit/Adafruit Unified Sensor @ 1.1.14